set_property SRC_FILE_INFO {cfile:C:/Users/azati/Own_IR_Standard/FPGA_Part/Own_IR_transmitter.srcs/constrs_1/new/constrains.xdc rfile:../../../Own_IR_transmitter.srcs/constrs_1/new/constrains.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN T14   IOSTANDARD LVCMOS33 } [get_ports { ir_out_0 }]; #IO_L5P_T0_34 Sch=ar[0]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U12   IOSTANDARD LVCMOS33 } [get_ports { ir_out_1 }]; #IO_L2N_T0_34 Sch=ar[1]
