webtalk_init -webtalk_dir C:/Users/azati/Own_IR_transmitter/Own_IR_transmitter.sim/sim_1/behav/xsim/xsim.dir/IR_transmitter_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Sep 16 20:27:08 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "50f231e6-e5a7-448b-a4b0-41f000c97c91" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "ea0bfc580968425e92463d3bfbca55a0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i9-14900HX" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2419 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "70 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "8.45_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "16532_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1100387289 -regid "" -xml C:/Users/azati/Own_IR_transmitter/Own_IR_transmitter.sim/sim_1/behav/xsim/xsim.dir/IR_transmitter_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/azati/Own_IR_transmitter/Own_IR_transmitter.sim/sim_1/behav/xsim/xsim.dir/IR_transmitter_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/azati/Own_IR_transmitter/Own_IR_transmitter.sim/sim_1/behav/xsim/xsim.dir/IR_transmitter_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
