# ir_out_0  = FPGA Pin T14  = ARDUINO D0 (Digital 0)
set_property -dict {PACKAGE_PIN T14 IOSTANDARD LVCMOS33} [get_ports {ir_out_0}] ; # PYNQ-Z2: ARDUINO D0 (D0)
# ir_out_1  = FPGA Pin U12  = ARDUINO D1 (Digital 1)
set_property -dict {PACKAGE_PIN U12 IOSTANDARD LVCMOS33} [get_ports {ir_out_1}] ; # PYNQ-Z2: ARDUINO D1 (D1)
# ir_out_2  = FPGA Pin U13  = ARDUINO D2 (Digital 2)
set_property -dict {PACKAGE_PIN U13 IOSTANDARD LVCMOS33} [get_ports {ir_out_2}] ; # PYNQ-Z2: ARDUINO D2 (D2)
# ir_out_3  = FPGA Pin V13  = ARDUINO D3 (Digital 3)
set_property -dict {PACKAGE_PIN V13 IOSTANDARD LVCMOS33} [get_ports {ir_out_3}] ; # PYNQ-Z2: ARDUINO D3 (D3)
# ir_out_4  = FPGA Pin V15  = ARDUINO D4 (Digital 4)
set_property -dict {PACKAGE_PIN V15 IOSTANDARD LVCMOS33} [get_ports {ir_out_4}] ; # PYNQ-Z2: ARDUINO D4 (D4)
# ir_out_5  = FPGA Pin T15  = ARDUINO D5 (Digital 5)
set_property -dict {PACKAGE_PIN T15 IOSTANDARD LVCMOS33} [get_ports {ir_out_5}] ; # PYNQ-Z2: ARDUINO D5 (D5)
# ir_out_6  = FPGA Pin R16  = ARDUINO D6 (Digital 6)
set_property -dict {PACKAGE_PIN R16 IOSTANDARD LVCMOS33} [get_ports {ir_out_6}] ; # PYNQ-Z2: ARDUINO D6 (D6)
# ir_out_7  = FPGA Pin U17  = ARDUINO D7 (Digital 7)
set_property -dict {PACKAGE_PIN U17 IOSTANDARD LVCMOS33} [get_ports {ir_out_7}] ; # PYNQ-Z2: ARDUINO D7 (D7)
# ir_out_8  = FPGA Pin V17  = ARDUINO D8 (Digital 8)
set_property -dict {PACKAGE_PIN V17 IOSTANDARD LVCMOS33} [get_ports {ir_out_8}] ; # PYNQ-Z2: ARDUINO D8 (D8)
# ir_out_9  = FPGA Pin V18  = ARDUINO D9 (Digital 9)
set_property -dict {PACKAGE_PIN V18 IOSTANDARD LVCMOS33} [get_ports {ir_out_9}] ; # PYNQ-Z2: ARDUINO D9 (D9)
# ir_out_10 = FPGA Pin T16  = ARDUINO D10 (Digital 10)
set_property -dict {PACKAGE_PIN T16 IOSTANDARD LVCMOS33} [get_ports {ir_out_10}] ; # PYNQ-Z2: ARDUINO D10 (D10)
# ir_out_11 = FPGA Pin R17  = ARDUINO D11 (Digital 11)
set_property -dict {PACKAGE_PIN R17 IOSTANDARD LVCMOS33} [get_ports {ir_out_11}] ; # PYNQ-Z2: ARDUINO D11 (D11)
# ir_out_12 = FPGA Pin P18  = ARDUINO D12 (Digital 12)
set_property -dict {PACKAGE_PIN P18 IOSTANDARD LVCMOS33} [get_ports {ir_out_12}] ; # PYNQ-Z2: ARDUINO D12 (D12)
# ir_out_13 = FPGA Pin N17  = ARDUINO D13 (Digital 13)
set_property -dict {PACKAGE_PIN N17 IOSTANDARD LVCMOS33} [get_ports {ir_out_13}] ; # PYNQ-Z2: ARDUINO D13 (D13)
# ir_out_14 = FPGA Pin Y11  = ARDUINO A0 (Analog 0)
set_property -dict {PACKAGE_PIN Y11 IOSTANDARD LVCMOS33} [get_ports {ir_out_14}] ; # PYNQ-Z2: ARDUINO A0 (A0)
# ir_out_15 = FPGA Pin Y12  = ARDUINO A1 (Analog 1)
set_property -dict {PACKAGE_PIN Y12 IOSTANDARD LVCMOS33} [get_ports {ir_out_15}] ; # PYNQ-Z2: ARDUINO A1 (A1)
# ir_out_16 = FPGA Pin W11  = ARDUINO A2 (Analog 2)
set_property -dict {PACKAGE_PIN W11 IOSTANDARD LVCMOS33} [get_ports {ir_out_16}] ; # PYNQ-Z2: ARDUINO A2 (A2)
# ir_out_17 = FPGA Pin V11  = ARDUINO A3 (Analog 3)
set_property -dict {PACKAGE_PIN V11 IOSTANDARD LVCMOS33} [get_ports {ir_out_17}] ; # PYNQ-Z2: ARDUINO A3 (A3)
# ir_out_18 = FPGA Pin T5   = ARDUINO A4 (Analog 4)
set_property -dict {PACKAGE_PIN T5  IOSTANDARD LVCMOS33} [get_ports {ir_out_18}] ; # PYNQ-Z2: ARDUINO A4 (A4)
# ir_out_19 = FPGA Pin U10   = ARDUINO A5 (Analog 5)
set_property -dict {PACKAGE_PIN U10 IOSTANDARD LVCMOS33} [get_ports {ir_out_19}]; #PYNQ-Z2: ARDUINO A5(A5)
# ir_out_20 = FPGA Pin Y19  = PMODA_1 (JA1)
set_property -dict {PACKAGE_PIN Y19 IOSTANDARD LVCMOS33} [get_ports {ir_out_20}] ; # PYNQ-Z2: PMODA JA1 (top row, pin 1)
# ir_out_21 = FPGA Pin Y18  = PMODA_2 (JA2)
set_property -dict {PACKAGE_PIN Y18 IOSTANDARD LVCMOS33} [get_ports {ir_out_21}] ; # PYNQ-Z2: PMODA JA2 (top row, pin 2)
# ir_out_22 = FPGA Pin Y17  = PMODA_3 (JA3)
set_property -dict {PACKAGE_PIN Y17 IOSTANDARD LVCMOS33} [get_ports {ir_out_22}] ; # PYNQ-Z2: PMODA JA3 (top row, pin 3)
# ir_out_23 = FPGA Pin Y16  = PMODA_4 (JA4)
set_property -dict {PACKAGE_PIN Y16 IOSTANDARD LVCMOS33} [get_ports {ir_out_23}] ; # PYNQ-Z2: PMODA JA4 (top row, pin 4)

